{
	'name' : "mycmp",
	'author' : "Ashok Dhudla",
	'version' : "1.0",
	'images' : 'images/mycmpaccnt.png',
	'category' : 'Practise',
	'depends' : ['base','base_setup','base_status','mail', 'resource','web_kanban'],
	'demo_xml' : [],
	'data' : ['wizard/test_wizard_view.xml',
	'mycompany_view.xml',
	'security/mycompany_security.xml',
	'security/ir.model.access.csv',
	'mycompany_workflow.xml',
	'mycompany_config_view.xml',
	],
	'installable' : True,
	'auto_install' : False,
	'application' : True,
}